language: node_js
sudo: true
node_js:
- stable
script:
- npm test
env:
  global:
  - CF_APP=visual-recognition-demo
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=demos
  - secure: "R58YETGYrJ010Zys/9ajvKx4I6PGrZe0OPRpr4rCwkpE6cbbUsOqGcnFWA1GwKxia8L+LNyCwhdhKcZ5QmVBQJu/aUrQTPF4gZ3mm8M2I5u8mI3L9KYQLVAfA+HDAz9EdesM4fc8RLHE/Hvy2olBgSdqP7PFUNTDZURHP9um2YU="
  - secure: "cz8WfWOmv3f3pprylCaRQdKtg7h0mxjVjRtWMWUSUzQ7f26ISVml9h19JycIJ5yLUTz6luFZeP7aohqhIA/c3r4MR8sj17Cmj5WcvkhPgt0kJFpaCA02QzAn1H0HVqFmnrWAVYRkAyOlUzKnnptjtf6KFYO1K9sPHiP2EMwY0PM="
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
    - cf-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/visual-recognition-nodejs
  skip_cleanup: true
notifications:
  email: false
